(deftheme spacemacs-dark
  "Created 2021-11-04.")

(custom-theme-set-variables
 'spacemacs-dark
 '(ansi-color-names-vector ["#0a0814" "#f2241f" "#67b11d" "#b1951d" "#4f97d7" "#a31db1" "#28def0" "#b2b2b2"]))

(custom-theme-set-faces
 'spacemacs-dark
 '(cursor ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(custom-button ((((class color) (min-colors 89)) :background "#212026" :foreground "#b2b2b2" :box (:line-width 2 :style released-button))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :background "#292e34" :slant normal))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7" :slant normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#ce537a" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#292b2e"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2"))))
 '(header-line ((((class color) (min-colors 89)) :background "#212026")))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444155"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#86dc2f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#29422d" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#444155" :foreground "#86dc2f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7"))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(region ((((class color) (min-colors 89)) (:background "#444155" :extend t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "#292b2e"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#b2b2b2"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#212026"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#5d4d7a"))))
 '(company-template-field ((((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#ce537a"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#4f97d7"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2"))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d" :extend t)))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#4f97d7")))
 '(diff-header ((((class color) (min-colors 89)) :background "#373040" :foreground "#bc6ec5" :extend t)))
 '(diff-file-header ((((class color) (min-colors 89)) :background "#373040" :foreground "#cbc1d5" :extend t)))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d" :extend t)))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#4f97d7")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#292b2e")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#4f97d7" :foreground "#292b2e")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#292b2e")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f" :extend t)))
 '(diff-hl-insert ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#67b11d")))
 '(diff-hl-delete ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#f2241f")))
 '(diff-hl-change ((((class color) (min-colors 89)) :background "#4f97d7" :foreground "#4f97d7")))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a31db1" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(evil-ex-lazy-highlight ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "#292b2e"))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 89)) (:background "#3c2a2c" :foreground "#f2241f"))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 89)) (:background "#293235" :foreground "#67b11d"))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :underline t))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:background "#444155" :inherit bold :extend t))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:inherit bold))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#4f97d7" :underline t))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b1951d" :underline t))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#67b11d" :underline t))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#44505c" :background "#212026" :inherit default))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#212026" :inherit line-number))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#222226" :box (:color "#5d4d7a" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#bc6ec5"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :box (:color "#5d4d7a" :line-width 1)))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:inherit match))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#b2b2b2"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#212026"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#5d4d7a"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "#67b11d")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "#b1951d")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :underline t))))
 '(show-paren-match-expression ((((class color) (min-colors 89)) (:background "#29422d"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold :underline t))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:background "#444155" :inherit bold))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:inherit bold))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:foreground "#4f97d7" :underline t))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b1951d" :underline t))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:foreground "#67b11d" :underline t))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:background nil :foreground "#2d9574"))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:background "#bc6ec5" :foreground "#292b2e"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background nil :foreground "#dc752f"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background nil :foreground "#c56ec3"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background nil :foreground "#c56ec3"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background nil :foreground "#5d4d7a"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background nil :foreground "#5d4d7a"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#dc752f"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(default ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2")))))

(provide-theme 'spacemacs-dark)
